# -*- coding: utf-8 -*-
"""BaiTap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VmI8OrFa6yAkIbkBpfXH1t0ysX-bawVa
"""

list1 = [1,10,20,5,60,30,10,9,10]
list2 = []
for x in list1:
  if x!=10:
    list2.append(x)
print(list2)

A = ["A", "B", "C", "D", "E", "F"]
B = [1,2,3,4,5,6]

Dict = dict(zip(A ,B))
print(Dict)

Person = {
    "name": "Quoc Nam",
    "age": 28,
    "salary": 8000,
    "city": "Tuy Hoa"
}
keyToRemove = ["name", "salary"]
for x in keyToRemove:
  if x in Person:
    Person.pop(x)
Person

from google.colab import files
uploaded = files.upload()
print(uploaded['mobile_data.csv'][:200].decode('utf-8')+ '...')
import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['mobile_data.csv'].decode('utf-8')))
df

peoples_df = pd.read_csv('./mobile_data.csv')
peoples_df.head(5)
peoples_df.tail(5)


# print(df.isnull().sum())
# modifiedDf = df.fillna("NaN")
# print(modifiedDf.isnull().sum())

from google.colab import files
uploaded = files.upload()
print(uploaded['mobile_data.csv'][:200].decode('utf-8')+ '...')
import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['mobile_data.csv'].decode('utf-8')))
df
na_values={
'price':["?","n.a"],
'stroke':["?","n.a"],
'horsepower':["?","n.a"],
'peak-rpm':["?","n.a"],
'average-mileage':["?","n.a"]}